// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package sqlc

import (
	"context"
	"time"
)

const countEventsByType = `-- name: CountEventsByType :one
SELECT COUNT(*) FROM events WHERE event_type = $1
`

func (q *Queries) CountEventsByType(ctx context.Context, eventType string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventsByType, eventType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (user_id, event_type, timestamp)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertEventParams struct {
	UserID    string
	EventType string
	Timestamp time.Time
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertEvent, arg.UserID, arg.EventType, arg.Timestamp)
	var id int32
	err := row.Scan(&id)
	return id, err
}
