// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"
)

type Event struct {
	ID        int32
	UserID    string
	EventType string
	Timestamp time.Time
}
